version: '3.4'

services:
  donationcamp:
    image: ${DOCKER_REGISTRY-}donationcamp
    build:
      context: .
      dockerfile: DonationCamp/Dockerfile

  persondocument:
    image: ${DOCKER_REGISTRY-}persondocument
    build:
      context: .
      dockerfile: Person/Dockerfile

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGOID_ENV=test
    ports:
      - 27017:27017
    volumes:       - /usr/local/share/mongo:/data/db

  prometheus:
    image: prom/prometheus:v2.11.1
    volumes:
      - /usr/local/share/prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090' 

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    
 